# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Animation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod 'Then'
  # Pods for Animation

  target 'AnimationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AnimationUITests' do
    # Pods for testing
  end

end
