disabled_rules:
- explicit_acl
- explicit_top_level_acl
- explicit_type_interface
- explicit_enum_raw_value 
- no_extension_access_modifier
- no_grouping_extension
- multiline_literal_brackets
- vertical_whitespace_between_cases

opt_in_rules:
- anyobject_protocol
- array_init
- attributes
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- conditional_returns_on_newline
- contains_over_first_not_nil
- convenience_type
- discouraged_object_literal
- discouraged_optional_boolean
- discouraged_optional_collection
- dynamic_inline
- empty_count
- empty_string
- empty_xctest_method
- explicit_init
- extension_access_modifier
- fallthrough
- fatal_error_message
- file_name
- first_where
- last_where
- force_unwrapping
- function_default_parameter_at_end
- identical_operands
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- large_tuple
- legacy_random
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- mark
- modifier_order
- multiline_arguments
- multiline_function_chains
- multiline_parameters
- multiline_arguments_brackets
- multiline_parameters_brackets
- multiline_literal_brackets
- nimble_operator
- number_separator
- nslocalizedstring_key
- object_literal
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefixed_toplevel_constant
- private_action
- private_outlet
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- redundant_type_annotation
- required_enum_case
- shorthand_operator
- single_test_class
- sorted_first_last
- sorted_imports
- static_operator
- strong_iboutlet
- strict_fileprivate
- switch_case_on_newline
- toggle_bool
- todo
- trailing_closure
- unavailable_function
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- unused_import
- unused_private_declaration
- vertical_parameter_alignment_on_call
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- yoda_condition
- xct_specific_matcher

excluded:
  - Pods

attributes:
  always_on_same_line: ["@discardableResult", "@objc", "@IBAction", "@IBDesignable"]

line_length: 
  warning: 160
  ignores_function_declarations: true
  ignores_comments: true

nesting:
  type_level: 2

type_body_length: 500 

file_length: 700

function_parameter_count: 6

warning_threshold: 2

conditional_returns_on_newline:
  if_only: true 

identifier_name:
  excluded:
    - id
    - x
    - y

file_name:
  excluded: [Util.swift]

