# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RickAndMorty' do

  use_frameworks!

  pod 'Kingfisher', '~> 5.0'
  pod 'SwiftLint'
  pod 'RealmSwift'

  # Pods for RickAndMorty

end
