# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Memes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'
  pod 'SwiftLint'
  pod 'RealmSwift'
  pod 'DeepDiff'
  
  target 'MemesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MemesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
