# Uncomment the next line to define a global platform for your project
# platform :ios, '12.1'

use_frameworks!
target 'HomeTaskNumberOne' do
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'AlamofireImage'
  pod 'Kingfisher'
  pod 'SwiftLint'

end
