# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Pokemons' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Kingfisher'
  pod 'SwiftLint'

  # Pods for Pokemons

  target 'PokemonsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
