# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RickAndMorty' do
  use_frameworks!

  pod 'Kingfisher'
  pod 'SwiftLint'
  pod 'RealmSwift'
  pod 'DeepDiff'

  target 'RickAndMortyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
