platform :ios, '10.0'

target 'RickAndMorty' do
  use_frameworks!

  pod 'Kingfisher'
  pod 'SwiftLint'
  pod 'RealmSwift'

  target 'RickAndMortyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
