# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Pictures' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pictures
	
	pod 'SwiftLint'

  target 'PicturesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PicturesUITests' do
    # Pods for testing
  end

end
