# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mtg Cards' do
  use_frameworks!

  # Pods for Mtg Cards
   pod 'SwiftLint'
   pod 'Reusable'
end
