# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'Kingfisher'
  pod 'SwiftLint'
  # Pods for NewsAPI

end
