# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RMProject' do
  use_frameworks!

  pod 'Kingfisher'
  pod 'SwiftLint'

  target 'RMProjectTests' do
    inherit! :search_paths

  end

end
